name: Release

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        required: true
        default: '0'
      minorVersion:
        required: true
        default: '1'

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: macos-latest
    env:
      releaseVersion: ${{ github.event.inputs.majorVersion }}.${{ github.event.inputs.minorVersion }}.${{ github.run_number }}
    steps:
      - name: Version
        run: echo Releasing version $releaseVersion
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      # Publish osx-x64
      - name: Publish osx-x64
        run: dotnet publish -r osx-x64 -p:Configuration=Release -p:DebugType=None -p:DebugSymbols=false -p:Version=${{env.releaseVersion}}
      - name: Zip osx-x64
        run: (cd CosmosExplorer.Avalonia/bin/Release/net8.0/osx-x64/publish ; zip -r LiteCosmosExplorer_osx-x64.zip *)
      # Publish osx-arm64
      - name: Publish osx-arm64
        run: dotnet publish -r osx-arm64 -p:Configuration=Release -p:DebugType=None -p:DebugSymbols=false -p:Version=${{env.releaseVersion}}
      - name: Zip osx-arm64
        run: (cd CosmosExplorer.Avalonia/bin/Release/net8.0/osx-arm64/publish ; zip -r LiteCosmosExplorer_osx-arm64.zip *)
     
     
